### ISSUE TITLE
Форма добавления задания: исправить причину ошибки в поле "Работа"

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#12]
Форма создания задачи:

1. Заполнить все поля валидными данными, кроме поля "Работа"
2. В поле "Работа" ввести буквенное значение из 10 символов
3. Нажать "Сохранить"

Ожидаемый результат:
Причина ошибки: недопустимый символ

Полученный результат:
Причина ошибки: "Работа не должна быть меньше 1 и больше 9 символов"

**Comment by vliplianina** [comment]
Принято.
Будьте внимательнее к формулировкам: 
- нужно исправить не причину ошибки, а текст сообщения об ошибке. Причина - это ввод некорректных данных.
- не "задание" (как указано в заголовке", а "задача" (как верно указано в описании. Может иметь разный смысл в рамках одного проекта.
