### ISSUE TITLE
Форма добавления задания: возможность сохранения без назначения исполнителя

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#13]
Форма добавления задания:
1. Заполнить все поля валидными данными
2. Выбор исполнителя оставить пустым
3. Нажать "Сохранить"

Ожидаемый результат:
Ошибка: не выбран исполнитель задачи

Полученный результат:
Сохранение происходит успешно, задача создана.

**Comment by vliplianina** [comment]
Принято.
