### ISSUE TITLE
Редактирование проекта: запись не сохраняется при редактировании какого-либо из полей, кроме поля "Название"

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#2]
**В разделе "Проекты" изменить какую-либо запись из списка отображенных:**

1. Найти необходимую запись (проект)
2. Нажать "Изменить"
3. В появившейся форме изменить любое поле, кроме поля "Название"
4. Нажать "Сохранить"

**Получено:**
Под полем "Название" появляется запись уведомления об ошибке "Проект с таким названием уже существует".

**Ожидаемо**:
Запись успешно сохранилась с измененными данными и отобразилась в разделе "Проекты"

**Comment by vliplianina** [comment]
Принято.
