### ISSUE TITLE
Удаление записи: при удалении записи автоматическое изменение значения идентификатора

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#3]
В разделе "Проекты" ("Задачи"/"Персоны") производим удаление записи из списка отображаемых:

1. Находим нужный проект
2. Нажимаем "Удалить"

Получено:
Запись удалена. Список отображаемых записей уменьшается. Значения всех идентификаторов остаются прежними.

Ожидаемо:
При удалении записи сделать автоматическое изменение нумерации идентификаторов.

**Comment by vliplianina** [comment]
Принято.
Рекомендация: в ожидаемом результате запроса на улучшение необходимо аргументировать надобность внедрения изменения, если это не очевидно. 
Идентификатор используется для распознавания записи, поэтому изменение номера идентификатора может привести к тому, что пользователь не сможет найти необходимую запись в случае, когда другие атрибуты записи идентичны или изменены.
