### ISSUE TITLE
Добавить сортировку по алфавиту в разделе "Проекты" по столбцу "Название"

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#4]
Просмотреть записи в разделе "Проекты":

1. Зайти в раздел "Проекты"
2. Просмотреть записи

Получено:
Все записи отображаются не отсортированными.

Ожидаемо:
Для удобства поиска проектов отсортировать записи по полю "Название" по алфавиту.

**Comment by vliplianina** [comment]
Принято.
