### ISSUE TITLE
В полях "Имя"/"Фамилия"/"Отчество" указать только буквенные допустимые типы вводимых данных 

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#5]
Зайти в раздел "Персоны"
Выбрать запись
Нажать "Изменить"
В любом из полей "Имя"/"Фамилия"/"Отчество" ввести числовые значения
Нажать "Сохранить"

Получено:
Запись сохранилась с измененными данными.

Ожидаемо:
Указать только буквенные допустимые значения типов данных, и при заполнении полей "Имя"/"Фамилия"/"Отчество" не буквенными значениями после нажатия "Сохранить", отображать уведомление о некорректном заполнении данных полей.

**Comment by Mariia5656** [comment]
Зайти в раздел "Персоны"
Выбрать запись
Нажать "Изменить"
В любом из полей "Имя"/"Фамилия"/"Отчество" ввести числовые значения
Нажать "Сохранить"

Получено:
Запись сохранилась с измененными данными.

Ожидаемо:
Указать только буквенные допустимые значения типов данных, и при заполнении полей "Имя"/"Фамилия"/"Отчество" не буквенными значениями после нажатия "Сохранить", отображать уведомление о некорректном заполнении данных полей.

**Comment by vliplianina** [comment]
Принято.
Рекомендации:
1. Не забывать нумеровать шаги 
2. Аккуратно предлагать ограничения возможностей пользователя: для указанных полей с буквенными значениями будет востребован ввод некоторых спец.символов, таких как дефис и апостроф
