### ISSUE TITLE
Удаление записей: любой пользователь имеет возможность удалять любую запись

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#6]
При переходе по ссылке доступ к удалению записей имеется у каждого, кто по этой ссылке перешел.

Получено:
Запись успешно удаляется

Предложение по улучшению: Добавить возможность авторизации пользователей и настроить ограничения по доступу к удалению записей путем разграничения прав.

**Comment by vliplianina** [comment]
Не дефект.
Разграничение прав не реализовано, авторизация отсутствует.
Прошу переформулировать в improvement.
Реализация фичи планируется в будущих версиях приложения.

**Comment by Mariia5656** [comment]
исправлено

**Comment by vliplianina** [comment]
Принято.
