### ISSUE TITLE
Форма ввода персоны: поле "Имя" (лаб. 3)

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#7]
Необходимо уточнить, какие типы значений являются валидными для заполнения (кириллица, латиница, цифры и т.д.), а также уточнить максимальное и минимальное допустимое количество вводимых символов. Необходимо уточнить, является ли поле обязательным для заполнения, доступно ли для редактирования.

**Comment by vliplianina** [comment]
Обновлено в [требованиях](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п.7 "Форма ввода персоны (исполнителя)" 

Замечания:
1) По заголовку непонятно, в чём заключается суть запроса. Пример: "Форма ввода персоны: _уточнить требования_ к полю "Имя"    
2) Запросы нужно регистрировать в репозитории команды, чтобы другие участники видели ответы: https://github.com/vliplianina/team-9b-volunteers/issues

Перенесите, пожалуйста, вместе с новой формулировкой.

**Comment by Mariia5656** [comment]
Сделано
