### ISSUE TITLE
Форма ввода персоны: поле "Фамилия" (лаб. 3)

### ISSUE THREAD

**Issue by Mariia5656** [Mariia5656/testing_labs#8]
Необходимо уточнить, какие типы значений являются валидными для заполнения (кириллица, латиница, цифры и т.д.), а также уточнить максимальное и минимальное допустимое количество вводимых символов. Необходимо уточнить, является ли поле обязательным для заполнения, доступно ли для редактирования.

**Comment by vliplianina** [comment]
Обновлено в [требованиях](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md) п.7 "Форма ввода персоны (исполнителя)" 

Замечания аналогичны issue #7

**Comment by Mariia5656** [comment]
Сделано
